#!/bin/bash
#
# Faenza VPN Setup Script for Linux (AWS/Ubuntu/Debian/Amazon Linux)
#
# This script installs and configures vpnc for Cisco IPSec VPN connection.
#
# Usage: ./setup-vpn-linux.sh
#
# Requirements:
#   - Linux (Ubuntu, Debian, Amazon Linux, RHEL)
#   - sudo privileges
#   - Environment variables set in .env file
#

set -e

# Load environment variables from .env if it exists
if [ -f ".env" ]; then
    export $(grep -v '^#' .env | xargs)
elif [ -f "../.env" ]; then
    export $(grep -v '^#' ../.env | xargs)
fi

# Configuration
VPN_SERVER="${VPN_SERVER:-195.62.179.98}"
VPN_USERNAME="${VPN_USERNAME}"
VPN_PASSWORD="${VPN_PASSWORD}"
VPN_SHARED_SECRET="${VPN_SHARED_SECRET}"
VPN_GROUP_NAME="${VPN_GROUP_NAME:-Memoraiz}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}=== Faenza VPN Setup for Linux ===${NC}"
echo ""

# Validate required variables
missing_vars=()
[ -z "$VPN_USERNAME" ] && missing_vars+=("VPN_USERNAME")
[ -z "$VPN_PASSWORD" ] && missing_vars+=("VPN_PASSWORD")
[ -z "$VPN_SHARED_SECRET" ] && missing_vars+=("VPN_SHARED_SECRET")

if [ ${#missing_vars[@]} -gt 0 ]; then
    echo -e "${RED}Error: Missing required environment variables:${NC}"
    for var in "${missing_vars[@]}"; do
        echo "  - $var"
    done
    echo ""
    echo "Please set these variables in your .env file or export them."
    exit 1
fi

echo "VPN Configuration:"
echo "  Server:   $VPN_SERVER"
echo "  Username: $VPN_USERNAME"
echo "  Group:    $VPN_GROUP_NAME"
echo ""

# Detect package manager and install vpnc
install_vpnc() {
    if command -v apt-get &> /dev/null; then
        echo "Detected Debian/Ubuntu system"
        sudo apt-get update
        sudo apt-get install -y vpnc
    elif command -v yum &> /dev/null; then
        echo "Detected RHEL/Amazon Linux system"
        sudo yum install -y vpnc || {
            # If vpnc is not in standard repos, try EPEL
            sudo yum install -y epel-release
            sudo yum install -y vpnc
        }
    elif command -v dnf &> /dev/null; then
        echo "Detected Fedora/RHEL 8+ system"
        sudo dnf install -y vpnc
    else
        echo -e "${RED}Error: Unsupported package manager. Please install vpnc manually.${NC}"
        exit 1
    fi
}

# Check if vpnc is installed
if ! command -v vpnc &> /dev/null; then
    echo "vpnc is not installed. Installing..."
    install_vpnc
    echo -e "${GREEN}vpnc installed successfully.${NC}"
else
    echo -e "${GREEN}vpnc is already installed.${NC}"
fi

# Create vpnc configuration directory
sudo mkdir -p /etc/vpnc

# Create vpnc configuration file
CONFIG_FILE="/etc/vpnc/faenza.conf"
echo "Creating VPN configuration at $CONFIG_FILE..."

sudo tee "$CONFIG_FILE" > /dev/null << EOF
# Faenza VPN Configuration
# Auto-generated by setup-vpn-linux.sh

IPSec gateway $VPN_SERVER
IPSec ID $VPN_GROUP_NAME
IPSec secret $VPN_SHARED_SECRET
Xauth username $VPN_USERNAME
Xauth password $VPN_PASSWORD

# Optional settings for better compatibility
# NAT Traversal Mode cisco-udp
# DPD idle timeout (R) 300
EOF

# Secure the configuration file
sudo chmod 600 "$CONFIG_FILE"
sudo chown root:root "$CONFIG_FILE"

echo -e "${GREEN}VPN configuration created.${NC}"

# Create convenience scripts
echo "Creating convenience scripts..."

# Connect script
sudo tee /usr/local/bin/faenza-vpn-connect > /dev/null << 'EOF'
#!/bin/bash
echo "Connecting to Faenza VPN..."
sudo vpnc /etc/vpnc/faenza.conf
if [ $? -eq 0 ]; then
    echo "VPN connected successfully!"
    echo "To disconnect: faenza-vpn-disconnect"
else
    echo "VPN connection failed!"
    exit 1
fi
EOF
sudo chmod +x /usr/local/bin/faenza-vpn-connect

# Disconnect script
sudo tee /usr/local/bin/faenza-vpn-disconnect > /dev/null << 'EOF'
#!/bin/bash
echo "Disconnecting from Faenza VPN..."
sudo vpnc-disconnect
if [ $? -eq 0 ]; then
    echo "VPN disconnected successfully!"
else
    echo "VPN disconnection failed or was not connected."
fi
EOF
sudo chmod +x /usr/local/bin/faenza-vpn-disconnect

# Status script
sudo tee /usr/local/bin/faenza-vpn-status > /dev/null << 'EOF'
#!/bin/bash
if ip link show tun0 &> /dev/null; then
    echo "VPN Status: CONNECTED"
    ip addr show tun0 | grep inet
else
    echo "VPN Status: DISCONNECTED"
fi
EOF
sudo chmod +x /usr/local/bin/faenza-vpn-status

echo -e "${GREEN}Convenience scripts created:${NC}"
echo "  - faenza-vpn-connect    (connect to VPN)"
echo "  - faenza-vpn-disconnect (disconnect from VPN)"
echo "  - faenza-vpn-status     (check VPN status)"
echo ""

# Configure sudoers for passwordless vpnc (optional, for automation)
echo "Configuring sudoers for passwordless VPN operations..."
SUDOERS_FILE="/etc/sudoers.d/faenza-vpn"

# Check if the application user exists, default to current user
APP_USER="${SUDO_USER:-$(whoami)}"

sudo tee "$SUDOERS_FILE" > /dev/null << EOF
# Allow $APP_USER to run vpnc commands without password
$APP_USER ALL=(ALL) NOPASSWD: /usr/sbin/vpnc
$APP_USER ALL=(ALL) NOPASSWD: /usr/sbin/vpnc-disconnect
EOF
sudo chmod 440 "$SUDOERS_FILE"

echo -e "${GREEN}Sudoers configured for user: $APP_USER${NC}"
echo ""

# Test connection
read -p "Do you want to test the VPN connection now? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "Testing VPN connection..."
    if sudo vpnc /etc/vpnc/faenza.conf; then
        echo -e "${GREEN}✓ VPN connected successfully!${NC}"
        
        # Test connectivity to Oracle server
        ORACLE_HOST="${ORACLE_HOST:-192.168.0.204}"
        echo "Testing connectivity to Oracle server ($ORACLE_HOST)..."
        if ping -c 1 -W 5 "$ORACLE_HOST" &> /dev/null; then
            echo -e "${GREEN}✓ Oracle server is reachable!${NC}"
        else
            echo -e "${YELLOW}⚠ Oracle server not reachable. Check firewall rules.${NC}"
        fi
        
        # Disconnect
        echo "Disconnecting test connection..."
        sudo vpnc-disconnect
    else
        echo -e "${RED}✗ VPN connection failed!${NC}"
        echo "Check the credentials and server address."
    fi
fi

echo ""
echo -e "${GREEN}=== Setup Complete ===${NC}"
echo ""
echo "Commands:"
echo "  Connect:    faenza-vpn-connect"
echo "  Disconnect: faenza-vpn-disconnect"
echo "  Status:     faenza-vpn-status"
echo ""
echo "The application will automatically connect to VPN when needed."

